var editorSettings = {
  "dictionary": "EN_US",
  "enableSpellChecking": true,
  "spellcheckerErrorLimit": 150, // limit of errors per screen before considered wrong language
  "theme": "vscodelight",
  "font": "Consolas",
  "fontSize": 14,
  "lineHeight": 1.45,
  "padding": 15,
  "maxWidth": 0,
  "highlightActiveLine": true,
  "wrapText": true,
  "clickableLinks": true,
  "showLineNumbers": false,
  "showInvisibles": false,
  "showPrintMargin": false,
  "printMargin": 100,
  "wrapMargin": 0,
  "keyboardHandler": "ace", 
  "tabSize": 4,
  "useSoftTabs": true,
  "enableBulletAutoCompletion": false,
  "isDebug": false,
  "linefeedMode": "windows"
};
